<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 3 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record (MetadataEntry*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
]>
<HealthData locale="de_DE">
 <ExportDate value="2017-01-25 20:11:49 +0100"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="1980-01-05" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeANegative" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeII"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="Health" sourceVersion="9.3.2" unit="cm" creationDate="2016-06-12 10:41:28 +0100" startDate="2016-06-12 10:41:00 +0100" endDate="2016-06-12 10:41:00 +0100" value="175">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="Health" sourceVersion="9.3.2" unit="cm" creationDate="2016-07-08 07:31:11 +0100" startDate="2016-07-08 07:31:00 +0100" endDate="2016-07-08 07:31:00 +0100" value="180">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="9.3.2" unit="kg" creationDate="2016-06-12 10:41:57 +0100" startDate="2016-06-10 06:30:00 +0100" endDate="2016-06-10 06:30:00 +0100" value="88.8">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="9.3.2" unit="kg" creationDate="2016-06-12 21:07:47 +0100" startDate="2016-06-12 21:07:00 +0100" endDate="2016-06-12 21:07:00 +0100" value="99.9">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="FitnessBand1" sourceVersion="10.2" device="FitnessBand1" unit="count/min" creationDate="2017-01-14 21:54:54 +0100" startDate="2017-01-14 21:54:54 +0100" endDate="2017-01-14 21:54:54 +0100" value="60"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="FitnessBand1" sourceVersion="10.2" device="FitnessBand1" unit="count/min" creationDate="2017-01-16 09:20:49 +0100" startDate="2017-01-16 09:20:49 +0100" endDate="2017-01-16 09:20:49 +0100" value="62"/>
 <Record type="HKQuantityTypeIdentifierBodyFatPercentage" sourceName="Health" sourceVersion="9.3.2" unit="%" creationDate="2016-07-01 14:26:26 +0100" startDate="2016-07-01 06:30:00 +0100" endDate="2016-07-01 06:30:00 +0100" value="0.15">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyFatPercentage" sourceName="Health" sourceVersion="9.3.2" unit="%" creationDate="2016-07-06 07:44:27 +0100" startDate="2016-07-06 07:44:00 +0100" endDate="2016-07-06 07:44:00 +0100" value="0.20">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierStepCount" sourceName="iPhone" sourceVersion="9.3.2" device="&lt;&lt;HKDevice: 0x000000000&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone8,4, software:9.3.2&gt;" unit="count" creationDate="2016-06-06 12:44:32 +0100" startDate="2016-06-06 11:55:57 +0100" endDate="2016-06-06 11:56:12 +0100" value="22"/>
 <Record type="HKQuantityTypeIdentifierStepCount" sourceName="iPhone" sourceVersion="9.3.2" device="&lt;&lt;HKDevice: 0x000000000&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone8,4, software:9.3.2&gt;" unit="count" creationDate="2016-06-06 12:44:32 +0100" startDate="2016-06-06 12:04:03 +0100" endDate="2016-06-06 12:09:55 +0100" value="78"/>
 <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="iPhone" sourceVersion="9.3.2" device="&lt;&lt;HKDevice: 0x000000000&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone8,4, software:9.3.2&gt;" unit="km" creationDate="2016-06-09 09:03:40 +0100" startDate="2016-06-09 08:13:13 +0100" endDate="2016-06-09 08:17:19 +0100" value="0.04723"/>
 <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="iPhone" sourceVersion="9.3.2" device="&lt;&lt;HKDevice: 0x000000000&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone8,4, software:9.3.2&gt;" unit="km" creationDate="2016-06-09 09:03:40 +0100" startDate="2016-06-09 08:31:47 +0100" endDate="2016-06-09 08:33:50 +0100" value="0.04913"/>
 <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="Runtastic" sourceVersion="6.8.1.191" unit="km" creationDate="2016-06-18 15:53:47 +0100" startDate="2016-06-18 15:12:09 +0100" endDate="2016-06-18 15:53:41 +0100" value="5.31038"/>
 <Record type="HKQuantityTypeIdentifierActiveEnergyBurned" sourceName="Mi Fit" sourceVersion="201612212139" unit="kcal" creationDate="2017-01-16 06:39:19 +0100" startDate="2017-01-15 12:50:00 +0100" endDate="2017-01-15 12:59:59 +0100" value="1"/>
 <Record type="HKQuantityTypeIdentifierActiveEnergyBurned" sourceName="Mi Fit" sourceVersion="201612212139" unit="kcal" creationDate="2017-01-16 21:57:50 +0100" startDate="2017-01-16 08:40:00 +0100" endDate="2017-01-16 08:49:59 +0100" value="27"/>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminA" sourceName="Health" sourceVersion="10.2" unit="mcg" creationDate="2017-01-13 06:57:54 +0100" startDate="2017-01-13 06:57:00 +0100" endDate="2017-01-13 06:57:00 +0100" value="3000">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminA" sourceName="Health" sourceVersion="10.2" unit="mcg" creationDate="2017-01-13 06:58:10 +0100" startDate="2017-01-12 17:57:00 +0100" endDate="2017-01-12 17:57:00 +0100" value="3000">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminC" sourceName="Health" sourceVersion="10.2" unit="mg" creationDate="2017-01-09 20:11:22 +0100" startDate="2017-01-09 19:00:00 +0100" endDate="2017-01-09 19:00:00 +0100" value="2000">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminC" sourceName="Health" sourceVersion="10.2" unit="mg" creationDate="2017-01-10 08:02:37 +0100" startDate="2017-01-10 08:02:00 +0100" endDate="2017-01-10 08:02:00 +0100" value="2000">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminD" sourceName="Health" sourceVersion="10.2" unit="mcg" creationDate="2017-01-10 08:05:17 +0100" startDate="2017-01-10 08:03:00 +0100" endDate="2017-01-10 08:03:00 +0100" value="140">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminD" sourceName="Health" sourceVersion="10.2" unit="mcg" creationDate="2017-01-12 07:46:05 +0100" startDate="2017-01-11 07:45:00 +0100" endDate="2017-01-11 07:45:00 +0100" value="140">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminK" sourceName="Health" sourceVersion="10.2" unit="mcg" creationDate="2017-01-13 06:57:01 +0100" startDate="2017-01-13 06:56:00 +0100" endDate="2017-01-13 06:56:00 +0100" value="1200">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryVitaminK" sourceName="Health" sourceVersion="10.2" unit="mcg" creationDate="2017-01-13 06:57:26 +0100" startDate="2017-01-12 18:00:00 +0100" endDate="2017-01-12 18:00:00 +0100" value="1200">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryMagnesium" sourceName="Health" sourceVersion="10.2" unit="mg" creationDate="2017-01-09 20:10:05 +0100" startDate="2017-01-09 19:30:00 +0100" endDate="2017-01-09 19:30:00 +0100" value="800">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryMagnesium" sourceName="Health" sourceVersion="10.2" unit="mg" creationDate="2017-01-15 09:40:10 +0100" startDate="2017-01-14 09:40:00 +0100" endDate="2017-01-14 09:40:00 +0100" value="800">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierDietaryCaffeine" sourceName="UP Coffee" sourceVersion="1.2" unit="mg" creationDate="2017-01-09 19:28:48 +0100" startDate="2017-01-09 12:00:00 +0100" endDate="2017-01-09 12:00:00 +0100" value="150"/>
 <Record type="HKQuantityTypeIdentifierDietaryCaffeine" sourceName="UP Coffee" sourceVersion="1.2" unit="mg" creationDate="2017-01-09 20:15:02 +0100" startDate="2017-01-09 12:00:00 +0100" endDate="2017-01-09 12:00:00 +0100" value="150"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Uhr" sourceVersion="50" device="&lt;&lt;HKDevice: 0x0000000000&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone8,4, software:10.0.1&gt;" creationDate="2016-09-14 05:30:15 +0100" startDate="2016-09-13 21:30:00 +0100" endDate="2016-09-14 05:30:15 +0100" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="_HKPrivateSleepAlarmUserWakeTime" value="2016-09-15 04:30:00 +0000"/>
  <MetadataEntry key="_HKPrivateSleepAlarmUserSetBedtime" value="2016-09-12 20:30:00 +0000"/>
  <MetadataEntry key="HKTimeZone" value="Europe/Berlin"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Uhr" sourceVersion="50" device="&lt;&lt;HKDevice: 0x0000000000&gt;, name:iPhone, manufacturer:Apple, model:iPhone, hardware:iPhone8,4, software:10.0.1&gt;" creationDate="2016-09-15 05:39:14 +0100" startDate="2016-09-14 21:30:00 +0100" endDate="2016-09-15 05:37:28 +0100" value="HKCategoryValueSleepAnalysisInBed">
  <MetadataEntry key="_HKPrivateSleepAlarmUserWakeTime" value="2016-09-15 04:30:00 +0000"/>
  <MetadataEntry key="_HKPrivateSleepAlarmUserSetBedtime" value="2016-09-13 20:30:00 +0000"/>
  <MetadataEntry key="HKTimeZone" value="Europe/Berlin"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-13 23:25:00 +0100" endDate="2017-01-13 23:46:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-13 23:47:00 +0100" endDate="2017-01-14 00:07:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 00:08:00 +0100" endDate="2017-01-14 00:19:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 00:20:00 +0100" endDate="2017-01-14 01:01:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 01:02:00 +0100" endDate="2017-01-14 01:26:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 01:27:00 +0100" endDate="2017-01-14 02:14:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 02:15:00 +0100" endDate="2017-01-14 02:25:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 02:26:00 +0100" endDate="2017-01-14 02:37:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 02:38:00 +0100" endDate="2017-01-14 02:54:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 02:55:00 +0100" endDate="2017-01-14 03:08:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 03:09:00 +0100" endDate="2017-01-14 03:36:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 03:37:00 +0100" endDate="2017-01-14 03:51:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 03:52:00 +0100" endDate="2017-01-14 04:39:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 04:40:00 +0100" endDate="2017-01-14 04:49:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 04:50:00 +0100" endDate="2017-01-14 04:59:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 05:00:00 +0100" endDate="2017-01-14 05:09:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 05:10:00 +0100" endDate="2017-01-14 05:31:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 05:32:00 +0100" endDate="2017-01-14 06:02:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 06:03:00 +0100" endDate="2017-01-14 06:31:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 06:32:00 +0100" endDate="2017-01-14 07:00:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 07:01:00 +0100" endDate="2017-01-14 07:28:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 07:29:00 +0100" endDate="2017-01-14 07:44:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-14 19:01:00 +0100" startDate="2017-01-14 07:45:00 +0100" endDate="2017-01-14 08:48:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-14 07:45:00 +0100" endDate="2017-01-14 08:48:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-14 22:33:00 +0100" endDate="2017-01-14 23:03:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-14 23:04:00 +0100" endDate="2017-01-14 23:48:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-14 23:49:00 +0100" endDate="2017-01-15 00:30:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 00:31:00 +0100" endDate="2017-01-15 00:40:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 00:41:00 +0100" endDate="2017-01-15 00:51:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 00:52:00 +0100" endDate="2017-01-15 01:04:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 01:05:00 +0100" endDate="2017-01-15 01:14:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 01:15:00 +0100" endDate="2017-01-15 01:35:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 01:36:00 +0100" endDate="2017-01-15 02:29:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 02:30:00 +0100" endDate="2017-01-15 02:41:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 02:42:00 +0100" endDate="2017-01-15 02:54:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 02:55:00 +0100" endDate="2017-01-15 03:12:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 03:13:00 +0100" endDate="2017-01-15 04:00:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 04:01:00 +0100" endDate="2017-01-15 04:38:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-15 09:39:56 +0100" startDate="2017-01-15 04:39:00 +0100" endDate="2017-01-15 08:09:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierSleepAnalysis" sourceName="Mi Fit" sourceVersion="201612212139" creationDate="2017-01-16 06:39:19 +0100" startDate="2017-01-15 04:39:00 +0100" endDate="2017-01-15 08:09:59 +0100" value="HKCategoryValueSleepAnalysisAsleep"/>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Headspace" sourceVersion="141" creationDate="2016-10-17 05:52:03 +0100" startDate="2016-10-17 05:33:59 +0100" endDate="2016-10-17 05:51:56 +0100"/>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Headspace" sourceVersion="141" creationDate="2016-10-20 15:04:22 +0100" startDate="2016-10-20 14:43:53 +0100" endDate="2016-10-20 15:00:31 +0100"/>
 <Workout workoutActivityType="HKWorkoutActivityTypeRunning" duration="30.81666666666667" durationUnit="min" totalDistance="4.83566259765625" totalDistanceUnit="km" totalEnergyBurned="367" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="6.8.1.191" creationDate="2016-06-14 06:22:13 +0100" startDate="2016-06-14 05:51:17 +0100" endDate="2016-06-14 06:22:06 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
 </Workout>
 <Workout workoutActivityType="HKWorkoutActivityTypeHiking" duration="105.1333333333333" durationUnit="min" totalDistance="0.5948336791992187" totalDistanceUnit="km" totalEnergyBurned="39" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="6.8.1.191" creationDate="2016-06-25 10:54:23 +0100" startDate="2016-06-25 09:09:12 +0100" endDate="2016-06-25 10:54:20 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
 </Workout>
 <Workout workoutActivityType="HKWorkoutActivityTypeOther" duration="90" durationUnit="min" totalDistance="0" totalDistanceUnit="km" totalEnergyBurned="350" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="6.8.4.195" creationDate="2016-07-03 21:29:38 +0100" startDate="2016-07-03 19:59:28 +0100" endDate="2016-07-03 21:29:28 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Workout>
 <Workout workoutActivityType="HKWorkoutActivityTypeRunning" duration="17.57449806928635" durationUnit="min" totalDistance="2.500891357421875" totalDistanceUnit="km" totalEnergyBurned="198" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="7.0.2.24" creationDate="2016-10-18 06:02:10 +0100" startDate="2016-10-18 05:42:59 +0100" endDate="2016-10-18 06:01:52 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2016-10-18 05:42:59 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypeResume" date="2016-10-18 05:43:01 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2016-10-18 05:44:50 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypeResume" date="2016-10-18 05:45:36 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2016-10-18 05:46:23 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypeResume" date="2016-10-18 05:46:31 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2016-10-18 05:48:57 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypeResume" date="2016-10-18 05:49:13 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2016-10-18 05:50:47 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypeResume" date="2016-10-18 05:50:53 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2016-10-18 06:01:51 +0100"/>
 </Workout>
 <Workout workoutActivityType="HKWorkoutActivityTypeSnowSports" duration="290.5054010033608" durationUnit="min" totalDistance="58.3130625" totalDistanceUnit="km" totalEnergyBurned="2263" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="7.1.1.63" creationDate="2017-01-21 16:19:40 +0100" startDate="2017-01-21 10:37:19 +0100" endDate="2017-01-21 16:19:37 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2017-01-21 13:28:11 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypeResume" date="2017-01-21 14:19:59 +0100"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2017-01-21 16:19:36 +0100"/>
 </Workout>
 <Workout workoutActivityType="HKWorkoutActivityTypeSnowSports" duration="132.956630285581" durationUnit="min" totalDistance="26.36252734375" totalDistanceUnit="km" totalEnergyBurned="1036" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="7.1.1.63" creationDate="2017-01-22 13:21:46 +0100" startDate="2017-01-22 11:08:45 +0100" endDate="2017-01-22 13:21:43 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2017-01-22 13:21:42 +0100"/>
 </Workout>
 <Workout workoutActivityType="HKWorkoutActivityTypeSnowSports" duration="56.9239054163297" durationUnit="min" totalDistance="10.7424111328125" totalDistanceUnit="km" totalEnergyBurned="443" totalEnergyBurnedUnit="kcal" sourceName="Runtastic" sourceVersion="7.1.1.63" creationDate="2017-01-22 16:04:05 +0100" startDate="2017-01-22 15:07:07 +0100" endDate="2017-01-22 16:04:03 +0100">
  <MetadataEntry key="HKIndoorWorkout" value="0"/>
  <WorkoutEvent type="HKWorkoutEventTypePause" date="2017-01-22 16:04:02 +0100"/>
 </Workout>
</HealthData>
